language: c
sudo: false
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$MACOS_UNIVERSAL" != "yes" ]]; then brew install glib cmocka; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$MACOS_UNIVERSAL" == "yes" ]]; then brew install glib --universal cmocka; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./install-cmocka-linux.sh; fi
script:
  - make && make test
# TODO make bindings enabled
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make clean && ./make.sh ios; fi
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
matrix:
  include:
  - os: osx
    compiler: clang
    env: MACOS_UNIVERSAL=yes
  - os: osx
    compiler: gcc
    env: MACOS_UNIVERSAL=yes
#  - os: osx
#    compiler: x86_64-w64-mingw32-gcc
addons:
  apt:
    packages:
    # mingw-w64 packages too old in precise
