version: 1.0-{build}

platform:
  - x64

environment:
  global:
    MSYS2_ARCH: x86_64
  matrix:
    - HOST_ARCH_ARG: --host=x86_64-w64-mingw32
      ADD_PATH: /mingw64/bin
    - HOST_ARCH_ARG: --host=i686-w64-mingw32
      ADD_PATH: /mingw32/bin

install:
  - C:\"Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Suy python2 make pkg-config mingw-w64-x86_64-glib2 mingw-w64-x86_64-toolchain"

build_script:
  - make.sh cross-win64
